"""test

Revision ID: 9cd23031a17b
Revises: f38da1353e3c
Create Date: 2024-08-07 10:41:26.111934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd23031a17b'
down_revision = 'f38da1353e3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_point', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('monthly_point')
        batch_op.drop_column('current_point')

    # ### end Alembic commands ###
