"""goal_point

Revision ID: bf49c53eb123
Revises: 7ad55a5bcfbe
Create Date: 2024-08-07 15:04:59.569937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf49c53eb123'
down_revision = '7ad55a5bcfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_point', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('goal_point')

    # ### end Alembic commands ###
